# Generated by Django 4.2.24 on 2025-09-19 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_options_alter_post_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Approved',
            new_name='approved',
        ),
    ]
